name: Release to JIRA
description: A GitHub action to automatically create releases on JIRA.
author: ulasozguler
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  jira_server:
    description: JIRA server
    required: true
  jira_project:
    description: JIRA project
    required: true
  jira_user:
    description: JIRA user
    required: true
  jira_token:
    description: JIRA user token
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Get or create Github release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        (
          gh api \
            --method GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} \
            --jq .body \
          || \
          gh api \
            --method POST /repos/${{ github.repository }}/releases \
              -f tag_name='${{ github.ref_name }}' \
              -f name='${{ github.ref_name }}' \
              -F generate_release_notes=true \
            --jq .body \
        ) > notes.md
    - name: Update JIRA
      shell: bash
      run: python ./src/main.py
      working-directory: ${{github.action_path}}
